name: CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Mostrar arquivos
        run: ls -la

      - name: Simular teste
        run: echo "CI funcionando com sucesso!"