name: Discord

on: 
    - push

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Discord Webhook
        uses: sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}            
          template: "avatar-with-link"